name: Convert

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      - name: Convert
        uses: johnlindquist/kit-action@main
        # Continue if it fails
        continue-on-error: true
        with:
          script: mp4-to-mp3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cat Files
        run: |
          ls -la
          ls -la ./.scripts         
          cat ./package.json 
          cat ./scripts/package.json
          cat ./.scripts/mp4-to-mp3.mjs
