name: Convert

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      - name: Convert
        users: johnlindquist/kit-action@main
        with:
          script: mp4-to-mp3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
